-- =============================================================================
-- Collecteo - Script de création de toutes les tables (PostgreSQL / Neon)
-- =============================================================================
-- Ce script reflète exactement le mapping JPA des entités du package
-- hei.school.add.entity. En temps normal, Hibernate crée et met à jour ces
-- tables automatiquement au démarrage (spring.jpa.hibernate.ddl-auto=update),
-- donc CE SCRIPT N'EST PAS OBLIGATOIRE pour faire fonctionner l'application.
--
-- Il est utile pour :
--   - inspecter/valider le schéma attendu sans lancer l'application,
--   - créer la base manuellement sur un nouvel environnement Neon,
--   - exécuter des requêtes SQL directement (psql, DBeaver, Neon SQL editor...).
--
-- Compatible PostgreSQL 14+ (Neon). Idempotent : peut être relancé sans erreur
-- grâce à IF NOT EXISTS / DROP ... CASCADE en commentaire ci-dessous si besoin.
-- =============================================================================

-- Pour repartir d'une base vierge, décommenter les lignes suivantes :
-- DROP TABLE IF EXISTS remboursements_prets CASCADE;
-- DROP TABLE IF EXISTS prets_bancaires CASCADE;
-- DROP TABLE IF EXISTS banque_transactions CASCADE;
-- DROP TABLE IF EXISTS comptes_bancaires CASCADE;
-- DROP TABLE IF EXISTS caisse_transactions CASCADE;
-- DROP TABLE IF EXISTS dettes CASCADE;
-- DROP TABLE IF EXISTS depenses CASCADE;
-- DROP TABLE IF EXISTS ventes CASCADE;
-- DROP TABLE IF EXISTS achats CASCADE;
-- DROP TABLE IF EXISTS produits CASCADE;
-- DROP TABLE IF EXISTS producteurs CASCADE;
-- DROP TABLE IF EXISTS clients CASCADE;
-- DROP TABLE IF EXISTS utilisateurs CASCADE;

-- =============================================================================
-- 1. utilisateurs (entity Utilisateur)
-- =============================================================================
CREATE TABLE IF NOT EXISTS utilisateurs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_utilisateur  VARCHAR(60)  NOT NULL UNIQUE,
    mot_de_passe     VARCHAR(255) NOT NULL, -- hash BCrypt, jamais le mot de passe en clair
    nom              VARCHAR(150) NOT NULL,
    role             VARCHAR(25)  NOT NULL
        CHECK (role IN ('ADMINISTRATEUR', 'COLLECTEUR', 'COMPTABLE', 'CAISSIER', 'RESPONSABLE')),
    actif            BOOLEAN      NOT NULL DEFAULT TRUE,
    date_creation    TIMESTAMP
);

-- =============================================================================
-- 2. clients (entity Client)
-- =============================================================================
CREATE TABLE IF NOT EXISTS clients (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR(150) NOT NULL,
    telephone       VARCHAR(30),
    adresse         VARCHAR(255),
    date_creation   TIMESTAMP
);

-- =============================================================================
-- 3. producteurs (entity Producteur)
-- =============================================================================
CREATE TABLE IF NOT EXISTS producteurs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR(150) NOT NULL,
    telephone       VARCHAR(30),
    adresse         VARCHAR(255),
    date_creation   TIMESTAMP
);

-- =============================================================================
-- 4. produits (entity Produit)
-- =============================================================================
CREATE TABLE IF NOT EXISTS produits (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom               VARCHAR(150)    NOT NULL,
    categorie         VARCHAR(100),
    prix_moyen_achat  NUMERIC(14, 2)  DEFAULT 0,
    prix_moyen_vente  NUMERIC(14, 2)  DEFAULT 0,
    quantite_stock    NUMERIC(14, 2)  DEFAULT 0,
    unite             VARCHAR(20)     DEFAULT 'kg'
);

-- =============================================================================
-- 5. comptes_bancaires (entity CompteBancaire)
-- =============================================================================
CREATE TABLE IF NOT EXISTS comptes_bancaires (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_banque      VARCHAR(100)    NOT NULL,
    numero_compte   VARCHAR(50),
    solde           NUMERIC(16, 2)  NOT NULL DEFAULT 0
);

-- =============================================================================
-- 6. achats (entity Achat) - dette du collecteur envers un producteur
-- =============================================================================
CREATE TABLE IF NOT EXISTS achats (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producteur_id    BIGINT          NOT NULL REFERENCES producteurs (id),
    produit_id       BIGINT          NOT NULL REFERENCES produits (id),
    quantite         NUMERIC(14, 2)  NOT NULL,
    prix_unitaire    NUMERIC(14, 2)  NOT NULL,
    montant_total    NUMERIC(14, 2)  NOT NULL,
    montant_paye     NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    montant_restant  NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    statut           VARCHAR(25)     NOT NULL
        CHECK (statut IN ('PAYEE', 'PARTIELLEMENT_PAYEE', 'IMPAYEE')),
    date_achat       TIMESTAMP       NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_achats_producteur_id ON achats (producteur_id);
CREATE INDEX IF NOT EXISTS idx_achats_produit_id ON achats (produit_id);

-- =============================================================================
-- 7. ventes (entity Vente) - créance du client envers le collecteur
-- =============================================================================
CREATE TABLE IF NOT EXISTS ventes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id        BIGINT          NOT NULL REFERENCES clients (id),
    produit_id       BIGINT          NOT NULL REFERENCES produits (id),
    quantite         NUMERIC(14, 2)  NOT NULL,
    prix_unitaire    NUMERIC(14, 2)  NOT NULL,
    montant_total    NUMERIC(14, 2)  NOT NULL,
    montant_paye     NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    montant_restant  NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    statut           VARCHAR(25)     NOT NULL
        CHECK (statut IN ('PAYEE', 'PARTIELLEMENT_PAYEE', 'IMPAYEE')),
    date_vente       TIMESTAMP       NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ventes_client_id ON ventes (client_id);
CREATE INDEX IF NOT EXISTS idx_ventes_produit_id ON ventes (produit_id);

-- =============================================================================
-- 8. caisse_transactions (entity CaisseTransaction) - mouvements d'argent liquide
-- =============================================================================
CREATE TABLE IF NOT EXISTS caisse_transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(10)     NOT NULL CHECK (type IN ('ENTREE', 'SORTIE')),
    categorie       VARCHAR(30)     NOT NULL
        CHECK (categorie IN ('VENTE', 'REMBOURSEMENT_CLIENT', 'APPORT_PROPRIETAIRE',
                              'AUTRE_ENTREE', 'ACHAT', 'SALAIRE', 'CARBURANT', 'TRANSPORT',
                              'DIVERS')),
    montant         NUMERIC(14, 2)  NOT NULL,
    description     VARCHAR(255),
    reference_id    BIGINT, -- référence facultative vers un Achat ou une Vente
    date            TIMESTAMP       NOT NULL
);

-- =============================================================================
-- 9. banque_transactions (entity BanqueTransaction)
-- =============================================================================
CREATE TABLE IF NOT EXISTS banque_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compte_bancaire_id  BIGINT          NOT NULL REFERENCES comptes_bancaires (id),
    type                VARCHAR(10)     NOT NULL CHECK (type IN ('ENTREE', 'SORTIE')),
    montant             NUMERIC(16, 2)  NOT NULL,
    description         VARCHAR(255),
    date                TIMESTAMP       NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_banque_transactions_compte_id ON banque_transactions (compte_bancaire_id);

-- =============================================================================
-- 10. prets_bancaires (entity PretBancaire)
-- =============================================================================
CREATE TABLE IF NOT EXISTS prets_bancaires (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compte_bancaire_id  BIGINT          NOT NULL REFERENCES comptes_bancaires (id),
    montant_emprunte    NUMERIC(16, 2)  NOT NULL,
    date_pret           DATE            NOT NULL,
    duree_mois          INTEGER         NOT NULL,
    taux_interet        NUMERIC(6, 3)   NOT NULL, -- taux annuel en %, ex 12.5 pour 12.5%
    mensualite          NUMERIC(16, 2)  NOT NULL,
    capital_restant     NUMERIC(16, 2)  NOT NULL,
    total_rembourse     NUMERIC(16, 2)  NOT NULL DEFAULT 0,
    prochaine_echeance  DATE,
    statut              VARCHAR(15)     NOT NULL
        CHECK (statut IN ('EN_COURS', 'SOLDE', 'EN_RETARD'))
);
CREATE INDEX IF NOT EXISTS idx_prets_bancaires_compte_id ON prets_bancaires (compte_bancaire_id);

-- =============================================================================
-- 11. remboursements_prets (entity RemboursementPret)
-- =============================================================================
CREATE TABLE IF NOT EXISTS remboursements_prets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pret_id     BIGINT          NOT NULL REFERENCES prets_bancaires (id),
    montant     NUMERIC(16, 2)  NOT NULL,
    date        TIMESTAMP       NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_remboursements_prets_pret_id ON remboursements_prets (pret_id);

-- =============================================================================
-- 12. depenses (entity Depense)
-- =============================================================================
CREATE TABLE IF NOT EXISTS depenses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categorie    VARCHAR(20)     NOT NULL
        CHECK (categorie IN ('TRANSPORT', 'CARBURANT', 'SALAIRES', 'TELEPHONE', 'INTERNET',
                              'REPARATION', 'BANQUE', 'TAXES', 'DIVERS')),
    montant      NUMERIC(14, 2)  NOT NULL,
    description  VARCHAR(255),
    date         TIMESTAMP       NOT NULL
);

-- =============================================================================
-- 13. dettes (entity Dette) - dettes hors achats (fournisseurs, prestataires...)
-- =============================================================================
CREATE TABLE IF NOT EXISTS dettes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fournisseur      VARCHAR(150)    NOT NULL,
    motif            VARCHAR(255),
    montant          NUMERIC(14, 2)  NOT NULL,
    montant_paye     NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    montant_restant  NUMERIC(14, 2)  NOT NULL,
    date_limite      DATE,
    statut           VARCHAR(25)     NOT NULL
        CHECK (statut IN ('PAYEE', 'PARTIELLEMENT_PAYEE', 'IMPAYEE')),
    date_creation    TIMESTAMP
);

-- =============================================================================
-- Fin du script - 13 tables créées
-- =============================================================================
